kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: main-repo
  namespace: cattle-fleet-system
spec:
  repo: https://github.com/alexandershelega/fleet-test
  branch: main
  paths:
  - repositories
  #- apps
  clientSecretName: githib-auth
  helmSecretName: helm-auth
  imageScanInterval: 1m 
  imageScanCommit:
    authorName: foo
    authorEmail: foo@bar.com
    messageTemplate: "update image"
