kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: main-repo2
  namespace: fleet-local
spec:
  repo: https://github.com/alexandershelega/fleet-test
  branch: main
  paths:
  - manifests
  clientSecretName: githib-auth
  helmSecretName: helm-auth
