kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: multicluster
  namespace: fleet-local
spec:
  repo: https://github.com/alexandershelega/fleet-test
  branch: main
  paths:
  - multicluster
  clientSecretName: githib-auth
  helmSecretName: helm-auth

  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        example: "true"
