kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: multicluster
  namespace: clusters
spec:
  repo: https://github.com/alexandershelega/fleet-test
  branch: main
  paths:
  - multicluster
  clientSecretName: githib-auth
  helmSecretName: helm-auth

  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
