apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4
  namespace: default
spec:
  selector:
    matchLabels:
      app: app4
  replicas: 1
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
      - name: app4
        image: nginx
        ports:
        - containerPort: 80

